//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public int id_attendance { get; set; }
        public int id_student { get; set; }
        public int id_subject { get; set; }
        public System.DateTime date { get; set; }
        public int id_visit { get; set; }
        public Nullable<int> grade { get; set; }
    
        public virtual students students { get; set; }
        public virtual subjects subjects { get; set; }
        public virtual visits visits { get; set; }
    }
}
