//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class control_types
    {
        public control_types()
        {
            this.exams = new HashSet<exams>();
        }
    
        public int id_control_type { get; set; }
        public string control_type_name { get; set; }
    
        public virtual ICollection<exams> exams { get; set; }
    }
}
