//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class days_of_week
    {
        public days_of_week()
        {
            this.schedules = new HashSet<schedules>();
        }
    
        public int id_day { get; set; }
        public string day_of_week { get; set; }
    
        public virtual ICollection<schedules> schedules { get; set; }
    }
}
