//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class enrollments
    {
        public enrollments()
        {
            this.attendance = new HashSet<attendance>();
            this.grades = new HashSet<grades>();
        }
    
        public int id_enrollment { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> id_course { get; set; }
        public Nullable<System.DateTime> enrollment_date { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<attendance> attendance { get; set; }
        public virtual courses courses { get; set; }
        public virtual students students { get; set; }
        public virtual ICollection<grades> grades { get; set; }
    }
}
