//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class exams
    {
        public int id_exam { get; set; }
        public int id_group { get; set; }
        public int id_subject { get; set; }
        public Nullable<int> id_control_type { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual control_types control_types { get; set; }
        public virtual groups groups { get; set; }
        public virtual subjects subjects { get; set; }
    }
}
