//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class faculties
    {
        public faculties()
        {
            this.specialties = new HashSet<specialties>();
        }
    
        public int id_faculty { get; set; }
        public string faculty_name { get; set; }
    
        public virtual ICollection<specialties> specialties { get; set; }
    }
}
