//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int id_feedback { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> id_course { get; set; }
        public string feedback_text { get; set; }
        public Nullable<System.DateTime> feedback_date { get; set; }
    
        public virtual courses courses { get; set; }
        public virtual students students { get; set; }
    }
}
