//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class grades
    {
        public int id_grade { get; set; }
        public Nullable<int> id_enrollment { get; set; }
        public Nullable<int> grade { get; set; }
        public Nullable<System.DateTime> date_assigned { get; set; }
    
        public virtual enrollments enrollments { get; set; }
    }
}
