//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class groups
    {
        public groups()
        {
            this.exams = new HashSet<exams>();
            this.schedules = new HashSet<schedules>();
            this.students = new HashSet<students>();
        }
    
        public int id_group { get; set; }
        public string group_number { get; set; }
        public int id_specialty { get; set; }
        public int course { get; set; }
    
        public virtual ICollection<exams> exams { get; set; }
        public virtual specialties specialties { get; set; }
        public virtual ICollection<schedules> schedules { get; set; }
        public virtual ICollection<students> students { get; set; }
    }
}
