//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class majors
    {
        public majors()
        {
            this.students = new HashSet<students>();
        }
    
        public int id_major { get; set; }
        public string major_name { get; set; }
        public Nullable<int> id_degree { get; set; }
    
        public virtual degrees degrees { get; set; }
        public virtual ICollection<students> students { get; set; }
    }
}
