//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class student_accountingEntities : DbContext
    {
        public student_accountingEntities()
            : base("name=student_accountingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<attendance> attendance { get; set; }
        public DbSet<control_types> control_types { get; set; }
        public DbSet<days_of_week> days_of_week { get; set; }
        public DbSet<exams> exams { get; set; }
        public DbSet<faculties> faculties { get; set; }
        public DbSet<genders> genders { get; set; }
        public DbSet<groups> groups { get; set; }
        public DbSet<qualifications> qualifications { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<schedules> schedules { get; set; }
        public DbSet<specialties> specialties { get; set; }
        public DbSet<students> students { get; set; }
        public DbSet<subjects> subjects { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<teachers> teachers { get; set; }
        public DbSet<visits> visits { get; set; }
    }
}
