//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class organization_memberships
    {
        public int id_membership { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> id_organization { get; set; }
        public Nullable<System.DateTime> join_date { get; set; }
    
        public virtual student_organizations student_organizations { get; set; }
        public virtual students students { get; set; }
    }
}
