//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedules
    {
        public int id_schedule { get; set; }
        public Nullable<int> id_course { get; set; }
        public Nullable<int> id_classroom { get; set; }
        public Nullable<int> id_instructor { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string day_of_week { get; set; }
    
        public virtual classrooms classrooms { get; set; }
        public virtual courses courses { get; set; }
        public virtual instructors instructors { get; set; }
    }
}
