//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class specialties
    {
        public specialties()
        {
            this.groups = new HashSet<groups>();
        }
    
        public int id_specialty { get; set; }
        public int id_faculty { get; set; }
        public string specialty_name { get; set; }
    
        public virtual faculties faculties { get; set; }
        public virtual ICollection<groups> groups { get; set; }
    }
}
