//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class students
    {
        public students()
        {
            this.enrollments = new HashSet<enrollments>();
            this.feedback = new HashSet<feedback>();
            this.organization_memberships = new HashSet<organization_memberships>();
        }
    
        public int id_student { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public Nullable<System.DateTime> enrollment_date { get; set; }
        public Nullable<int> id_major { get; set; }
    
        public virtual ICollection<enrollments> enrollments { get; set; }
        public virtual ICollection<feedback> feedback { get; set; }
        public virtual majors majors { get; set; }
        public virtual ICollection<organization_memberships> organization_memberships { get; set; }
    }
}
