//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_organizations
    {
        public student_organizations()
        {
            this.organization_memberships = new HashSet<organization_memberships>();
        }
    
        public int id_organization { get; set; }
        public string organization_name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<organization_memberships> organization_memberships { get; set; }
    }
}
