//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class subjects
    {
        public int id_subject { get; set; }
        public string subject_name { get; set; }
        public string subject_description { get; set; }
        public Nullable<int> id_course { get; set; }
    
        public virtual courses courses { get; set; }
    }
}
