//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class subjects
    {
        public subjects()
        {
            this.attendance = new HashSet<attendance>();
            this.exams = new HashSet<exams>();
            this.schedules = new HashSet<schedules>();
        }
    
        public int id_subject { get; set; }
        public int id_teacher { get; set; }
        public string subject_name { get; set; }
    
        public virtual ICollection<attendance> attendance { get; set; }
        public virtual ICollection<exams> exams { get; set; }
        public virtual ICollection<schedules> schedules { get; set; }
        public virtual teachers teachers { get; set; }
    }
}
