//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class teachers
    {
        public teachers()
        {
            this.subjects = new HashSet<subjects>();
        }
    
        public int id_teacher { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int id_role { get; set; }
        public int id_qualification { get; set; }
    
        public virtual qualifications qualifications { get; set; }
        public virtual roles roles { get; set; }
        public virtual ICollection<subjects> subjects { get; set; }
    }
}
