//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace students.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class visits
    {
        public visits()
        {
            this.attendance = new HashSet<attendance>();
        }
    
        public int id_visit { get; set; }
        public string visit_name { get; set; }
    
        public virtual ICollection<attendance> attendance { get; set; }
    }
}
